# Feeder 3.1 Data Compilation

### Importing Pandas

#### Packages

This provides more tools and functions not available in Python. Anadacona includes a feature which the pandas package is already installed.

Once the package has been installed, you can now import your file in you current python session using the imported button. If the file is not imported it will not be recognized and functions will be unavailble.

#### Pandas

Pandas enables you to store data with feature such as rows, columns, and headers, which is similar to Microsoft Excel. This software is beneficial because it allows you to filter large datasets to the sepcific topics you are targeting. Pandas has a varitey of tools which you can use to manage large datasets.

 Make sure the file that you import is saved as .csv

You will import data file that we need to use with python. You will only be using pandas not numpys.

You will first type "import pandas" following with "as pd"

In [1]:
import pandas as pd

### Creating a Dataframe

You should have downloaded the .csv file "CountyHealthData_2014-2015.csv". Store your copy in the same folder as this notebook. Save the document atleast one time into your directory.

Now you will create a dateframe object. your .csv file will be read by pandas.

#### Using pd.read_csv

pd.read_csv will read the data from your Comma Separated Values (csv) file. It will be defined as "df". Once you define the code, you will type "pd.read_csv" and inside the parenthesis and quotations you will type the entire name of the your .csv file.

In [2]:
df=pd.read_csv("CountyHealthData_2014-2015.csv")

### Exploring our dataframe

The purpose of ".dtype" will show you all the columns and the types of columns.
Type in the name of your new dta set "df" follow with .dtypes

Type in the the name of your new data set "df" follow with .dtypes

In [3]:
df.dtypes

State                                object
Region                               object
Division                             object
County                               object
FIPS                                  int64
                                     ...
Other primary care providers        float64
Median household income               int64
Children eligible for free lunch    float64
Homicide rate                       float64
Inadequate social support           float64
Length: 64, dtype: object

The purpose of .shape is to show you the number of columns and the number of row in the data set.

Type the name of your define data set which is "df" following with .shape

In [4]:
df.shape

(6109, 64)

If you want to know the total count of cell in your data set you can use .size. This will give you the number of cells in the dataframe.

Type the name of your defined data set "df" followed with .shape.

In [5]:
df.size

390976

If you want a preview of all the columns in you data set, .columns will reveal the title of each column in the data set.

Type the name of your define data set which is "df" following with .columns

In [6]:
df.columns

Index(['State', 'Region', 'Division', 'County', 'FIPS', 'GEOID', 'SMS Region',
       'Year', 'Premature death', 'Poor or fair health',
       'Poor physical health days', 'Poor mental health days',
       'Low birthweight', 'Adult smoking', 'Adult obesity',
       'Food environment index', 'Physical inactivity',
       'Access to exercise opportunities', 'Excessive drinking',
       'Alcohol-impaired driving deaths', 'Sexually transmitted infections',
       'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists',
       'Mental health providers', 'Preventable hospital stays',
       'Diabetic screening', 'Mammography screening', 'High school graduation',
       'Some college', 'Unemployment', 'Children in poverty',
       'Income inequality', 'Children in single-parent households',
       'Social associations', 'Violent crime', 'Injury deaths',
       'Air pollution - particulate matter', 'Drinking water violations',
       'Severe housing problems', 'Driving alone to work',
       'Long commute - driving alone', '2011 population estimate',
       'Population that is not proficient in English',
       'Population living in a rural area', 'Diabetes', 'HIV prevalence rate',
       'Premature age-adjusted mortality', 'Infant mortality',
       'Child mortality', 'Food insecurity', 'Limited access to healthy foods',
       'Motor vehicle crash deaths', 'Drug poisoning deaths',
       'Uninsured adults', 'Uninsured children', 'Health care costs',
       'Could not see doctor due to cost', 'Other primary care providers',
       'Median household income', 'Children eligible for free lunch',
       'Homicide rate', 'Inadequate social support'],
      dtype='object')

If you want a preview of the first  5 columns in the dataset, you will use the code .head.

Type the name of your define data set which is "df" following with .head()

In [7]:
df.head()

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
0,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2014,NaN,0.122,...,NaN,0.374,0.250,3791.0,0.185,216.0,69192,0.127,NaN,0.287
1,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2015,NaN,0.122,...,NaN,0.314,0.176,4837.0,0.185,254.0,74088,0.133,NaN,NaN
2,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2014,6827.0,0.125,...,15.37,0.218,0.096,6588.0,0.119,135.0,71094,0.319,6.29,0.160
3,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2015,6856.0,0.125,...,17.08,0.227,0.123,6582.0,0.119,148.0,76362,0.334,5.60,NaN
4,AK,West,Pacific,Bethel Census Area,2050,2050,Insuff Data,1/1/2014,13345.0,0.211,...,NaN,0.394,0.124,5860.0,0.200,169.0,41722,0.668,12.77,0.477

### Filtering Our Data

We want our data set to focus on areas in North Carolina and the effects of food insecurity on the health of the NC residences.

Since you want to filter the date to only states in North Carolina, you will want to use df["State"]. Then you will follow this with "==" and the desired state after which would be "NC".

In [19]:
df=df[df["State"] == "NC"]
df

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
3243,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2014,7123.0,0.192,...,10.48,0.259,0.073,8640.0,0.167,46.0,41394,0.444,4.94,0.202
3244,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2015,7291.0,0.192,...,12.38,0.249,0.088,9050.0,0.167,56.0,43001,0.455,4.60,NaN
3245,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2014,7974.0,0.178,...,22.74,0.240,0.077,9316.0,0.205,30.0,39655,0.417,6.27,0.273
3246,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2015,8079.0,0.178,...,24.04,0.239,0.076,9242.0,0.205,32.0,46064,0.449,7.20,NaN
3247,NC,South,South Atlantic,Alleghany County,37005,37005,Insuff Data,1/1/2014,8817.0,0.234,...,18.18,0.320,0.131,9585.0,0.210,55.0,34046,0.523,NaN,0.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3438,NC,South,South Atlantic,Wilson County,37195,37195,Region 20,1/1/2015,8028.0,0.159,...,7.31,0.262,0.079,9450.0,0.107,77.0,40772,0.556,9.60,NaN
3439,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2014,7893.0,0.207,...,18.45,0.252,0.097,10084.0,0.158,32.0,40012,0.422,3.76,0.241
3440,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2015,7258.0,0.207,...,20.21,0.242,0.094,10998.0,0.158,32.0,40998,0.455,NaN,NaN
3441,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2014,6872.0,0.193,...,20.79,0.268,0.110,7707.0,0.158,79.0,36019,0.477,NaN,0.176
3442,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2015,8917.0,0.193,...,28.02,0.246,0.091,7870.0,0.158,74.0,35866,0.469,NaN,NaN

You can check to see if your data was defined to your desire by typing in the name of your set. You would type "df"

In [20]:
df

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
3243,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2014,7123.0,0.192,...,10.48,0.259,0.073,8640.0,0.167,46.0,41394,0.444,4.94,0.202
3244,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2015,7291.0,0.192,...,12.38,0.249,0.088,9050.0,0.167,56.0,43001,0.455,4.60,NaN
3245,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2014,7974.0,0.178,...,22.74,0.240,0.077,9316.0,0.205,30.0,39655,0.417,6.27,0.273
3246,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2015,8079.0,0.178,...,24.04,0.239,0.076,9242.0,0.205,32.0,46064,0.449,7.20,NaN
3247,NC,South,South Atlantic,Alleghany County,37005,37005,Insuff Data,1/1/2014,8817.0,0.234,...,18.18,0.320,0.131,9585.0,0.210,55.0,34046,0.523,NaN,0.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3438,NC,South,South Atlantic,Wilson County,37195,37195,Region 20,1/1/2015,8028.0,0.159,...,7.31,0.262,0.079,9450.0,0.107,77.0,40772,0.556,9.60,NaN
3439,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2014,7893.0,0.207,...,18.45,0.252,0.097,10084.0,0.158,32.0,40012,0.422,3.76,0.241
3440,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2015,7258.0,0.207,...,20.21,0.242,0.094,10998.0,0.158,32.0,40998,0.455,NaN,NaN
3441,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2014,6872.0,0.193,...,20.79,0.268,0.110,7707.0,0.158,79.0,36019,0.477,NaN,0.176
3442,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2015,8917.0,0.193,...,28.02,0.246,0.091,7870.0,0.158,74.0,35866,0.469,NaN,NaN

You want to filter the data to the column that you desire for your data table. In this case we want state, country, year, food enivornment index, adult obesity, limited access to healthy foods, diabetes, and food insecurity. You will use .loc[] and input all comun titles inside the brackets.

In [35]:
df=x.loc[:,["State","County", "Food environment index","Adult obesity","Limited access to healthy foods","Diabetes","Food insecurity"]]
df

,State,County,Food environment index,Adult obesity,Limited access to healthy foods,Diabetes,Food insecurity
3243,NC,Alamance County,6.532,0.341,0.113,0.124,0.174
3244,NC,Alamance County,6.200,0.332,0.113,0.122,0.171
3245,NC,Alexander County,7.825,0.272,0.023,0.108,0.156
3246,NC,Alexander County,7.400,0.283,0.023,0.106,0.159
3247,NC,Alleghany County,7.561,0.247,0.014,0.114,0.174
...,...,...,...,...,...,...,...
3438,NC,Wilson County,5.900,0.373,0.028,0.130,0.226
3439,NC,Yadkin County,8.296,0.297,0.004,0.099,0.142
3440,NC,Yadkin County,8.000,0.301,0.004,0.097,0.145
3441,NC,Yancey County,8.001,0.287,0.000,0.109,0.159
3442,NC,Yancey County,7.700,0.271,0.000,0.116,0.160

### Exporting Our New Subset

Now that we've finished manipulating out data sets we can export it as .csv file. This data will be accessible to the public.

We will export the manipulated dataset by using RI_subset.to_csv("RI_subset.csv"). You will add the file name inside the pararenthesis.

You will replace "RI_subset" with the name of your define data set. In this case it would be "df".

In [30]:
df.to_csv("df", index=False)